version: '3'
services:
  jobmanager:
    image: apache/flink:1.18.1
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ../sql:/opt/sql
      - ../reference/libs/flink-faker-0.5.3.jar:/opt/flink/lib/flink-faker-0.5.3.jar
  
  taskmanager:
    image: apache/flink:1.18.1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
    volumes:
      - ../reference/libs/flink-faker-0.5.3.jar:/opt/flink/lib/flink-faker-0.5.3.jar